// Re-export all Prisma-generated types for use across web and mobile packages.
// This file is populated after Session 02 runs prisma generate in apps/api/.

export type {
    User,
    RefreshToken,
    EmailVerificationToken,
    PasswordResetToken,
    Province,
    City,
    Category,
    Product,
    Order,
    RentalBooking,
    RentalDeposit,
    SwapRequest,
    SwapNegotiationEvent,
    SwapOrderConfirmation,
    Swap,
    Payment,
    Wallet,
    WalletLedgerEntry,
    PayoutRequest,
    Review,
    Dispute,
    Notification,
    UserEcoScore,
    Wishlist,
    RecentlyViewed,
    PlatformSetting,
} from './generated/browser';

export {
    UserRole,
    AccountStatus,
    ProfileStatus,
    ProductCondition,
    ApprovalStatus,
    ProductStatus,
    RentType,
    OrderStatus,
    RentalStatus,
    DepositStatus,
    SwapStatus,
    NegotiationEventType,
    MoneyDirection,
    PaymentSourceType,
    PaymentGateway,
    PaymentStatus,
    WalletType,
    LedgerDirection,
    LedgerEntryType,
    PayoutStatus,
    DisputeStatus,
} from './generated/enums';
